<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Version>8.0.0.0</Version>
	<AssemblyVersion>8.0.0.0</AssemblyVersion>
	<FileVersion>8.0.0.0</FileVersion>
    <PackageId>UMapx</PackageId>
    <Company>Valery Asiryan</Company>
    <Authors>Valery Asiryan</Authors>
    <Product>UMapx</Product>
    <Copyright>Valery Asiryan, © 2015-2026</Copyright>
    <Description>Cross-platform .NET library for digital signal processing. Fast and optimized.</Description>
    <PackageProjectUrl>https://github.com/asiryan/UMapx</PackageProjectUrl>
    <RepositoryUrl>https://github.com/asiryan/UMapx</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>image video signal processing analytics streaming wavelet fourier analysis matrix decomposition transformation complex algebra</PackageTags>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageIcon>umapxnet.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <SignAssembly>false</SignAssembly>
    <AssemblyOriginatorKeyFile>umapxnet.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.1" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\readme.md" Pack="true" PackagePath="README.md" />
    <None Include="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="umapxnet.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
