using UMapx.Core;

namespace UMapx.Tests;

public partial class GeometryApiTests
{
    public static IEnumerable<object[]> RequiredApi()
    {
        yield return new object[] { typeof(PointInt), new[]
        {
            "Boolean Equals(Object obj)",
            "Boolean Equals(PointInt other)",
            "field static readonly PointInt Empty",
            "Int32 GetHashCode()",
            "interface IEquatable<PointInt>",
            "new(Int32 dw)",
            "new(Int32 x, Int32 y)",
            "new(SizeInt sz)",
            "property Boolean IsEmpty get browsable=False",
            "property Int32 X get set",
            "property Int32 Y get set",
            "static Boolean op_Equality(PointInt left, PointInt right)",
            "static Boolean op_Inequality(PointInt left, PointInt right)",
            "static PointFloat op_Implicit(PointInt p)",
            "static PointInt Add(PointInt pt, SizeInt sz)",
            "static PointInt Ceiling(PointFloat value)",
            "static PointInt op_Addition(PointInt pt, SizeInt sz)",
            "static PointInt op_Subtraction(PointInt pt, SizeInt sz)",
            "static PointInt Round(PointFloat value)",
            "static PointInt Subtract(PointInt pt, SizeInt sz)",
            "static PointInt Truncate(PointFloat value)",
            "static SizeInt op_Explicit(PointInt p)",
            "String ToString()",
            "Void Offset(Int32 dx, Int32 dy)",
            "Void Offset(PointInt p)",
        } };
        yield return new object[] { typeof(PointFloat), new[]
        {
            "Boolean Equals(Object obj)",
            "Boolean Equals(PointFloat other)",
            "field static readonly PointFloat Empty",
            "Int32 GetHashCode()",
            "interface IEquatable<PointFloat>",
            "new(Single x, Single y)",
            "new(Vector2 vector)",
            "property Boolean IsEmpty get browsable=False",
            "property Single X get set",
            "property Single Y get set",
            "static Boolean op_Equality(PointFloat left, PointFloat right)",
            "static Boolean op_Inequality(PointFloat left, PointFloat right)",
            "static PointFloat Add(PointFloat pt, SizeFloat sz)",
            "static PointFloat Add(PointFloat pt, SizeInt sz)",
            "static PointFloat op_Addition(PointFloat pt, SizeFloat sz)",
            "static PointFloat op_Addition(PointFloat pt, SizeInt sz)",
            "static PointFloat op_Explicit(Vector2 vector)",
            "static PointFloat op_Subtraction(PointFloat pt, SizeFloat sz)",
            "static PointFloat op_Subtraction(PointFloat pt, SizeInt sz)",
            "static PointFloat Subtract(PointFloat pt, SizeFloat sz)",
            "static PointFloat Subtract(PointFloat pt, SizeInt sz)",
            "static Vector2 op_Explicit(PointFloat point)",
            "String ToString()",
            "Vector2 ToVector2()",
        } };
        yield return new object[] { typeof(RectangleInt), new[]
        {
            "Boolean Contains(Int32 x, Int32 y)",
            "Boolean Contains(PointInt pt)",
            "Boolean Contains(RectangleInt rect)",
            "Boolean Equals(Object obj)",
            "Boolean Equals(RectangleInt other)",
            "Boolean IntersectsWith(RectangleInt rect)",
            "field static readonly RectangleInt Empty",
            "Int32 GetHashCode()",
            "interface IEquatable<RectangleInt>",
            "new(Int32 x, Int32 y, Int32 width, Int32 height)",
            "new(PointInt location, SizeInt size)",
            "property Boolean IsEmpty get browsable=False",
            "property Int32 Bottom get browsable=False",
            "property Int32 Height get set",
            "property Int32 Left get browsable=False",
            "property Int32 Right get browsable=False",
            "property Int32 Top get browsable=False",
            "property Int32 Width get set",
            "property Int32 X get set",
            "property Int32 Y get set",
            "property PointInt Location get set browsable=False",
            "property SizeInt Size get set browsable=False",
            "static Boolean op_Equality(RectangleInt left, RectangleInt right)",
            "static Boolean op_Inequality(RectangleInt left, RectangleInt right)",
            "static RectangleInt Ceiling(RectangleFloat value)",
            "static RectangleInt FromLTRB(Int32 left, Int32 top, Int32 right, Int32 bottom)",
            "static RectangleInt Inflate(RectangleInt rect, Int32 x, Int32 y)",
            "static RectangleInt Intersect(RectangleInt a, RectangleInt b)",
            "static RectangleInt Round(RectangleFloat value)",
            "static RectangleInt Truncate(RectangleFloat value)",
            "static RectangleInt Union(RectangleInt a, RectangleInt b)",
            "String ToString()",
            "Void Inflate(Int32 width, Int32 height)",
            "Void Inflate(SizeInt size)",
            "Void Intersect(RectangleInt rect)",
            "Void Offset(Int32 x, Int32 y)",
            "Void Offset(PointInt pos)",
        } };
        yield return new object[] { typeof(RectangleFloat), new[]
        {
            "Boolean Contains(PointFloat pt)",
            "Boolean Contains(RectangleFloat rect)",
            "Boolean Contains(Single x, Single y)",
            "Boolean Equals(Object obj)",
            "Boolean Equals(RectangleFloat other)",
            "Boolean IntersectsWith(RectangleFloat rect)",
            "field static readonly RectangleFloat Empty",
            "Int32 GetHashCode()",
            "interface IEquatable<RectangleFloat>",
            "new(PointFloat location, SizeFloat size)",
            "new(Single x, Single y, Single width, Single height)",
            "new(Vector4 vector)",
            "property Boolean IsEmpty get browsable=False",
            "property PointFloat Location get set browsable=False",
            "property Single Bottom get browsable=False",
            "property Single Height get set",
            "property Single Left get browsable=False",
            "property Single Right get browsable=False",
            "property Single Top get browsable=False",
            "property Single Width get set",
            "property Single X get set",
            "property Single Y get set",
            "property SizeFloat Size get set browsable=False",
            "static Boolean op_Equality(RectangleFloat left, RectangleFloat right)",
            "static Boolean op_Inequality(RectangleFloat left, RectangleFloat right)",
            "static RectangleFloat FromLTRB(Single left, Single top, Single right, Single bottom)",
            "static RectangleFloat Inflate(RectangleFloat rect, Single x, Single y)",
            "static RectangleFloat Intersect(RectangleFloat a, RectangleFloat b)",
            "static RectangleFloat op_Explicit(Vector4 vector)",
            "static RectangleFloat op_Implicit(RectangleInt r)",
            "static RectangleFloat Union(RectangleFloat a, RectangleFloat b)",
            "static Vector4 op_Explicit(RectangleFloat rectangle)",
            "String ToString()",
            "Vector4 ToVector4()",
            "Void Inflate(Single x, Single y)",
            "Void Inflate(SizeFloat size)",
            "Void Intersect(RectangleFloat rect)",
            "Void Offset(PointFloat pos)",
            "Void Offset(Single x, Single y)",
        } };
        yield return new object[] { typeof(SizeInt), new[]
        {
            "Boolean Equals(Object obj)",
            "Boolean Equals(SizeInt other)",
            "field static readonly SizeInt Empty",
            "Int32 GetHashCode()",
            "interface IEquatable<SizeInt>",
            "new(Int32 width, Int32 height)",
            "new(PointInt pt)",
            "property Boolean IsEmpty get browsable=False",
            "property Int32 Height get set",
            "property Int32 Width get set",
            "static Boolean op_Equality(SizeInt sz1, SizeInt sz2)",
            "static Boolean op_Inequality(SizeInt sz1, SizeInt sz2)",
            "static PointInt op_Explicit(SizeInt size)",
            "static SizeFloat op_Division(SizeInt left, Single right)",
            "static SizeFloat op_Implicit(SizeInt p)",
            "static SizeFloat op_Multiply(Single left, SizeInt right)",
            "static SizeFloat op_Multiply(SizeInt left, Single right)",
            "static SizeInt Add(SizeInt sz1, SizeInt sz2)",
            "static SizeInt Ceiling(SizeFloat value)",
            "static SizeInt op_Addition(SizeInt sz1, SizeInt sz2)",
            "static SizeInt op_Division(SizeInt left, Int32 right)",
            "static SizeInt op_Multiply(Int32 left, SizeInt right)",
            "static SizeInt op_Multiply(SizeInt left, Int32 right)",
            "static SizeInt op_Subtraction(SizeInt sz1, SizeInt sz2)",
            "static SizeInt Round(SizeFloat value)",
            "static SizeInt Subtract(SizeInt sz1, SizeInt sz2)",
            "static SizeInt Truncate(SizeFloat value)",
            "String ToString()",
        } };
        yield return new object[] { typeof(SizeFloat), new[]
        {
            "Boolean Equals(Object obj)",
            "Boolean Equals(SizeFloat other)",
            "field static readonly SizeFloat Empty",
            "Int32 GetHashCode()",
            "interface IEquatable<SizeFloat>",
            "new(PointFloat pt)",
            "new(Single width, Single height)",
            "new(SizeFloat size)",
            "new(Vector2 vector)",
            "PointFloat ToPointF()",
            "property Boolean IsEmpty get browsable=False",
            "property Single Height get set",
            "property Single Width get set",
            "SizeInt ToSize()",
            "static Boolean op_Equality(SizeFloat sz1, SizeFloat sz2)",
            "static Boolean op_Inequality(SizeFloat sz1, SizeFloat sz2)",
            "static PointFloat op_Explicit(SizeFloat size)",
            "static SizeFloat Add(SizeFloat sz1, SizeFloat sz2)",
            "static SizeFloat op_Addition(SizeFloat sz1, SizeFloat sz2)",
            "static SizeFloat op_Division(SizeFloat left, Single right)",
            "static SizeFloat op_Explicit(Vector2 vector)",
            "static SizeFloat op_Multiply(Single left, SizeFloat right)",
            "static SizeFloat op_Multiply(SizeFloat left, Single right)",
            "static SizeFloat op_Subtraction(SizeFloat sz1, SizeFloat sz2)",
            "static SizeFloat Subtract(SizeFloat sz1, SizeFloat sz2)",
            "static Vector2 op_Explicit(SizeFloat size)",
            "String ToString()",
            "Vector2 ToVector2()",
        } };
    }
}
